name: Context examples

on: ['push']

jobs:
  my-context:
    runs-on: self-hosted
    steps:
      - name: "My Step"
        run: echo "Hello! $MY_ACTION"
        env:
          MY_ACTION: ${{ github.action }}